# Generated by Django 4.2.5 on 2023-10-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menu_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_name',
        ),
    ]
